### ISSUE TITLE
mini audit additional scan requested 

### ISSUE THREAD

**Issue by winkelermatthias** [BytePhoenixData/BSCTokenSniper#11]
Seeing a few rugs happening where tokens get trasnfered and sold from burn address somehow. Do not know the exact details here and might be misinterpreting the issue: 

see chart with just a few transactions before rugpul: https://poocoin.app/tokens/0x9a1a8046d2648bd101c3bd6c6746055418686b7d 

the trasnaction that kills it:
https://bscscan.com/tx/0x0f218d5aece288d4223d232c10d5b603467cbf4a6af9777dbfd9062feef709af 

Could it be related to this: 
https://ethereum.stackexchange.com/questions/98215/why-is-it-considered-a-bad-practice-to-burn-tokens-to-0x0-when-creating-an-erc20 

Any way we can write a function to check for the inproper implementation of burn ?

Anyway thanks for opensourcing this, this is great work!

**Comment by geeks121** [comment]
Great idea .. and dx timelock too i thing,,

**Comment by BSC-Contarcts** [comment]
Hi therfore I have added the following into the sniper. i don´t want any tokens that have solidity 4 or 5 so they get ignored and fail.
I have tested it and it works.

I added the following:

config.json - > "checksolidity4": "True" at last line.
then bscsniper.py - > 
Line 98 : checksolidity4 = obj['checksolidity4']
Then in the mini audit:
elif ("0.4." in str(tokenContractCode['result'][0]['SourceCode'])) or "0.5." in str(tokenContractCode['result'][0]['SourceCode']) and checksolidity4 == "True": #check if solidity is 4.xx 
                    print(style.RED + "[FAIL] Contract uses wrong solidity.")


cehck: https://bscscan.com/address/0x26465EaB74FcDe4a29e613Af5Eb03cE907e43d8E#code

Works for me: 
![grafik](https://user-images.githubusercontent.com/88907310/130049197-86c02799-69c1-4ed7-914c-06e625be3b3e.png)

hope it helps. Now the mint funtkion is nor propor anymore because it scans for the word mint and all the enw reward tokens have this funktion so i am currently checking that too.

**Comment by geeks121** [comment]
can you pull it

**Comment by winkelermatthias** [comment]
I am testing it today, already running for an hour. Is this resolving the previous dumps as in the above transaction at requesT? So far it seems to be working as the 3 projects i bought into havent dumped to 0. Awesome!

**Comment by geeks121** [comment]
> I am testing it today, already running for an hour. Is this resolving the previous dumps as in the above transaction at requesT? So far it seems to be working as the 3 projects i bought into havent dumped to 0. Awesome!

may you add to test solidity5 or 6

**Comment by geeks121** [comment]
use small amount only ,, for testing i use 0.01 usd each token i buy

**Comment by geeks121** [comment]
> Hi therfore I have added the following into the sniper. i don´t want any tokens that have solidity 4 or 5 so they get ignored and fail.
> I have tested it and it works.
> 
> I added the following:
> 
> config.json - > "checksolidity4": "True" at last line.
> then bscsniper.py - > 
> Line 98 : checksolidity4 = obj['checksolidity4']
> Then in the mini audit:
> elif ("0.4." in str(tokenContractCode['result'][0]['SourceCode'])) or "0.5." in str(tokenContractCode['result'][0]['SourceCode']) and checksolidity4 == "True": #check if solidity is 4.xx 
>                     print(style.RED + "[FAIL] Contract uses wrong solidity.")
> 
> 
> cehck: https://bscscan.com/address/0x26465EaB74FcDe4a29e613Af5Eb03cE907e43d8E#code
> 
> Works for me: 
> ![grafik](https://user-images.githubusercontent.com/88907310/130049197-86c02799-69c1-4ed7-914c-06e625be3b3e.png)
> 
> hope it helps. Now the mint funtkion is nor propor anymore because it scans for the word mint and all the enw reward tokens have this funktion so i am currently checking that too.
> 

hi .. i added your script to my bscsnip fork and credited to you..

just neee another feature like timelock.. or token with limited token supply

**Comment by Sani0** [comment]
Hey guys,

i have these error when i'm using checksolidity but it's works without. anyone do know why ?

Thanks !
![Issue](https://user-images.githubusercontent.com/89406110/130476597-5ac32cc3-ee62-4a4b-819e-e28a7e258873.JPG)

**Comment by geeks121** [comment]
> Hey guys,
> 
> i have these error when i'm using checksolidity but it's works without. anyone do know why ?
> 
> Thanks !
> ![Issue](https://user-images.githubusercontent.com/89406110/130476597-5ac32cc3-ee62-4a4b-819e-e28a7e258873.JPG)
> 

you missing checksolidity4 in config.json

for example see in my fork for config.json with checksolidity4

**Comment by Sani0** [comment]
i confirm checksolidity4 is in config.json but still have the same messages

**Comment by geeks121** [comment]
> i confirm checksolidity4 is in config.json but still have the same messages

you miss coma after add the checksolidity.. go check again.

**Comment by Sani0** [comment]
Oh true ! Thanks alot ! it's works. 

Just a last question what we need to put for gas fee ? leave it to 300000 ? i have only transaction failed and have 0.2 bnb in wallet any tips ?

**Comment by BytePhoenixData** [comment]
I would just leave it at 300000 always works for me. What do u mean by only transaction failed

**Comment by Sani0** [comment]
I mean all the contract who pass the miniaudit result to transaction failed but counted as tokens bought do u guys have alot on failed ? or it's normal to have some failed and maybe one will be ok ?

**Comment by Buco11-dev** [comment]
Side note guys: Check the transaction confirmation section. I noticed it confirms failed transactions as successful because it always returns a 1. 
To Fix: Add ['result'] before ['status'] in txResult.
e.g. txResult = checkTransactionRequest.json()['result']['status']

**Comment by Buco11-dev** [comment]
Question for everyone who has tried and tested the bot:  

1.) Is the bot affected by the tax system most of these meme coins have built-in their smart contracts?

2.) I assume the bot is not affected by slippage since it's almost instant, however, some meme coins would specify minimum slippage eg 12% or so. Is the bot affected by this?

Insights will be very much appreciated, thanks!
