### ISSUE TITLE
Everything works except the buying part

### ISSUE THREAD

**Issue by roadmaus** [BytePhoenixData/BSCTokenSniper#8]
Thanks for this cool bot! 👍
Every 20 minutes or so a token passes the mini audit so I know it works.
But every time the transaction fails. Tried it on different platforms and with different gas prices and limits.
Should I have BNB or BSC or WBNB in my wallet?
Also should the bsc api key be connected to the wallet?

thanks a lot in advance

**Comment by BytePhoenixData** [comment]
Are you sure that the wallet address and private key are entered correctly in config file?

Also try setting gas price to 300000 instead of 200000. That was a mistake by me when I was testing it, have now just updated it.

Should just be regular BNB in your Binance smart chain wallet. 

I would recommend to use your own bscscan api key as I have just used mine by default, but only 5 requests / sec are allowed. If everyone uses it then you might not be able to get your request response.

**Comment by roadmaus** [comment]
Thanks a lot for the quick reply! 
I had the wrong private key entered. 
now it works perfectly :)

**Comment by Buco11-dev** [comment]
Thanks, man for sharing this cool tool. In relation to the inquiry above, can I use a stable coin instead of BNB to place purchases?
